### ISSUE TITLE
Bug trying to run example (related to GNormPlus)

### ISSUE THREAD

**Issue by jmcejuela** [Rostlab/nalaf#159]
```shell
python example_annotate.py -c /usr/local/bin/ -s "This is c.A1003G an example"
Due to a dependence on GNormPlus, running nalaf with -s and -d switches might take a long time.
Traceback (most recent call last):
  File "example_annotate.py", line 61, in <module>
    GNormPlusGeneTagger().tag(dataset, uniprot=True)
  File "/Users/jmcejuela/Work/hck/nalaf/nalaf/learning/taggers.py", line 153, in tag
    abstract = next(parts)
StopIteration
```

**Comment by jmcejuela** [comment]
@abojchevski likely to do with wrong doc format structure

**Comment by abojchevski** [comment]
The -d switch is broken... I am aware but did not document it. Sorry. Needs to be fixed either way.

**Comment by yanqiangmiffy** [comment]
excuse me。Has this bug been solved?Today ,I run the code,but console occurs the same errors

**Comment by yanqiangmiffy** [comment]
Why only pmids{15878741 12625412} that is in example given make it? others come out bugs?

**Comment by juanmirocks** [comment]
@yanqiangmiffy thanks for reporting -- first, curious: what is your use of nalaf?

The bug is actually kinda deprecated because in reality, after refactoring the nalaf code, the dependency of `GNormPlus` should not exist in nalaf, only in [nala](https://github.com/Rostlab/nala)

So the real solution would be to remove GNormPlus as dependency. Nonetheless, do you still need this code to run?
