### ISSUE TITLE
nalaf.download_data always failed, any workaround?

### ISSUE THREAD

**Issue by loveJasmine** [Rostlab/nalaf#177]
mldl@ub1604:~/ub16_prj/nalaf$ sudo python3 -m nalaf.download_data
[nltk_data] Downloading package punkt to /home/mldl/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Downloading parsing model
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

**Comment by juanmirocks** [comment]
Dear @loveJasmine thank you for your report.

This should have been fixed already.

Otherwise please let me know and reopen the issue

**Comment by loveJasmine** [comment]
ub16hp@UB16HP:~/ub16_prj/nalaf$ 
ub16hp@UB16HP:~/ub16_prj/nalaf$ sudo python3 -m nalaf.download_data
[nltk_data] Downloading package punkt to /home/ub16hp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Downloading parsing model
Traceback (most recent call last):
  File "/home/ub16hp/ub16_prj/nalaf/nalaf/download_data.py", line 21, in <module>
    spacy_en_download.main(data_size='parser', force=False)
  File "/usr/local/lib/python3.5/dist-packages/spacy/en/download.py", line 17, in main
    download('en', False)
  File "/usr/local/lib/python3.5/dist-packages/spacy/download.py", line 16, in download
    about.__models__.get(lang, lang))
  File "/usr/local/lib/python3.5/dist-packages/sputnik/__init__.py", line 159, in package
    pool = Pool(app_name, app_version, expand_path(data_path))
  File "/usr/local/lib/python3.5/dist-packages/sputnik/pool.py", line 19, in __init__
    super(Pool, self).__init__(app_name, app_version, path, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sputnik/package_list.py", line 33, in __init__
    self.load()
  File "/usr/local/lib/python3.5/dist-packages/sputnik/package_list.py", line 51, in load
    for package in self.packages():
  File "/usr/local/lib/python3.5/dist-packages/sputnik/package_list.py", line 47, in packages
    yield self.__class__.package_class(path=os.path.join(self.path, path))
  File "/usr/local/lib/python3.5/dist-packages/sputnik/package.py", line 15, in __init__
    super(Package, self).__init__(defaults=meta['package'])
KeyError: 'package'
ERROR Could not save spacy English parser model. Download model: en-1.1.0 --> and extract it in: /usr/local/lib/python3.5/dist-packages/spacy/data
ub16hp@UB16HP:~/ub16_prj/nalaf$

**Comment by juanmirocks** [comment]
Oh, thanks @loveJasmine ! Yes, we must indicate where to download the model: `en-1.1.0`

Try with this:

```shell
wget -q --show-progress https://s3.amazonaws.com/net.tagtog.prod.resources/deployment/en-1.1.0.tar.gz -P /tmp
tmp_target_path=$(python3 -c "import os; import spacy; print(os.path.join(os.path.dirname(spacy.__file__), 'data'))") && \
    mkdir -p $tmp_target_path && \
    tar xvzf /tmp/en-1.1.0.tar.gz -C $tmp_target_path
```

**Comment by loveJasmine** [comment]
not works
